package project_euler;

public class q44 {

	/**
	 *
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
	 */
	public static void main(String[] args) {

		int min = Integer.MAX_VALUE;
		
		for(int j = 1; j < 10000; j++) {
			for(int k = j + 1; k < 10000; k++) {
				long pj = j * (3 * j - 1) / 2;
				long pk = k * (3 * k - 1) / 2;
				
				long sum = pj + pk;
				long difference = Math.abs(pk - pj);
				
				double result = 1 + 4.0 * 3 * 2 * sum;
				double root = (1.0 + Math.pow(result, 0.5)) / (2.0 * 3);
				
				double result1 = 1 + 4.0 * 3 * 2 * difference;
				double root1 = (1.0 + Math.pow(result1, 0.5)) / (2.0 * 3);
				
				if(root == (int)root && root1 == (int)(root1)) {
					min = (int) Math.min(min, difference);
					System.out.println(root + " " + result + " " + j + " " + k + " " + sum + " " + difference);
				}
				
			}
		}
		
		System.out.println(min);


	}


}
