package project_euler;

public class q45 {

	/**
	 *
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
	 */
	public static void main(String[] args) {

		for(long i = 286; true; i++) {

			long triangle = i * (i + 1)/2;


			double result = 1 + 4.0 * 3 * 2 * triangle;
			double root = (1.0 + Math.pow(result, 0.5)) / (2.0 * 3);
			
			double result1 = 1 + 4.0 * 2 * triangle;
			double root1 = (1.0 + Math.pow(result1, 0.5)) / (2.0 * 2);
			
			if(root == (int)root && root1 == (int)root1) {
				System.out.println(i + " " + triangle);
				break;
			}

		}


	}


}
